package com.itdr.dao;

import com.itdr.pojo.Category;
import java.util.List;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_category
     *
     * @mbg.generated Mon Oct 29 15:48:44 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_category
     *
     * @mbg.generated Mon Oct 29 15:48:44 CST 2018
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_category
     *
     * @mbg.generated Mon Oct 29 15:48:44 CST 2018
     */
    Category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_category
     *
     * @mbg.generated Mon Oct 29 15:48:44 CST 2018
     */
    List<Category> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_category
     *
     * @mbg.generated Mon Oct 29 15:48:44 CST 2018
     */
    int updateByPrimaryKey(Category record);

    /**
     * 查询子类（平级）
     * */

    List<Category> findChildCategory(Integer categoryId);

    /**
     * 判断charity子节点是否已经存在
     * */

    int  slectSameChildNode(String categoryName);
}