package com.itdr.dao;

import com.itdr.pojo.Shopping;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ShoppingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_shopping
     *
     * @mbg.generated Mon Oct 29 15:48:44 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_shopping
     *
     * @mbg.generated Mon Oct 29 15:48:44 CST 2018
     */
    int insert(Shopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_shopping
     *
     * @mbg.generated Mon Oct 29 15:48:44 CST 2018
     */
    Shopping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_shopping
     *
     * @mbg.generated Mon Oct 29 15:48:44 CST 2018
     */
    List<Shopping> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_shopping
     *
     * @mbg.generated Mon Oct 29 15:48:44 CST 2018
     */
    int updateByPrimaryKey(Shopping record);

    /**
     * 根据shoppingId和userId删除地址
     * */
   int deleteByuserIdAndShoppingId(@Param("userId") Integer userId,
                                   @Param("shoppingId") Integer shoppingId);

   int updateBySelectiveKey(Shopping shopping);
}